import type { AuditResult, LeadStatus, Priority } from "../types";

export type SampleClinic = {
  slug: string;
  business_name: string;
  website: string;
  domain: string;
  city: string;
  state: string;
  country: string;
  public_phone: string;
  public_email: string | null;
  source_url: string;
  category: string;
  notes: string;
  tags: string[];
  status: LeadStatus;
  audit: AuditResult;
  score: number;
  priority: Priority;
  reasons: string[];
  estimated_value: "low" | "medium" | "high";
  seedDraft?: boolean;
  seedApproval?: "pending" | "approved" | "rejected";
  response?: string | null;
};

export const SAMPLE_CLINICS: SampleClinic[] = [
  {
    slug: "bright-smile-austin",
    business_name: "Bright Smile Family Dentistry",
    website: "https://brightsmileaustin.example",
    domain: "brightsmileaustin.example",
    city: "Austin",
    state: "TX",
    country: "United States",
    public_phone: "(512) 555-0142",
    public_email: "hello@brightsmileaustin.example",
    source_url: "https://brightsmileaustin.example",
    category: "Dental clinic",
    notes: "DEMO. Independent family practice. Site is a static brochure.",
    tags: ["demo", "family"],
    status: "DRAFT_READY",
    audit: {
      appointment_available: false,
      chatbot_present: false,
      faq_present: false,
      lead_capture_present: false,
      after_hours_help: false,
      mobile_experience: "average",
      contact_flow_clear: false,
      activity_signals: "strong",
      opportunities: [
        "No online booking",
        "No chatbot for after-hours questions",
        "No structured FAQ",
      ],
      observations: [
        "Public site lists a phone number but no appointment request form",
        "No chatbot widget in the public HTML",
        "Hours are listed as an image, not as structured text",
      ],
      confidence: 86,
    },
    score: 90,
    priority: "very_high",
    reasons: [
      "No chatbot detected on the public website",
      "No obvious online appointment assistant",
      "Weak or missing lead capture",
      "Weak FAQ / help experience",
      "No after-hours assistance detected",
      "Unclear contact or appointment flow",
      "Strong public business activity signals",
    ],
    estimated_value: "high",
    seedDraft: true,
    seedApproval: "pending",
  },
  {
    slug: "parkside-atlanta",
    business_name: "Parkside Dental Associates",
    website: "https://parksidedental.example",
    domain: "parksidedental.example",
    city: "Atlanta",
    state: "GA",
    country: "United States",
    public_phone: "(404) 555-0190",
    public_email: null,
    source_url: "https://parksidedental.example/contact",
    category: "Dental clinic",
    notes: "DEMO. Multi-dentist practice. Contact page is a mailto link.",
    tags: ["demo", "group"],
    status: "QUALIFIED",
    audit: {
      appointment_available: false,
      chatbot_present: false,
      faq_present: false,
      lead_capture_present: true,
      after_hours_help: false,
      mobile_experience: "poor",
      contact_flow_clear: false,
      activity_signals: "strong",
      opportunities: ["Replace mailto contact with appointment intake", "Add after-hours FAQ answers"],
      observations: [
        "Contact page uses a mailto: link rather than an appointment form",
        "No chatbot present",
        "Viewport meta is missing; layout is desktop-first",
      ],
      confidence: 82,
    },
    score: 91,
    priority: "very_high",
    reasons: [
      "No chatbot detected on the public website",
      "No obvious online appointment assistant",
      "Has a form, but no appointment flow",
      "Weak FAQ / help experience",
      "No after-hours assistance detected",
      "Unclear contact or appointment flow",
      "Mobile experience looks poor",
      "Strong public business activity signals",
    ],
    estimated_value: "high",
  },
  {
    slug: "pine-ridge-denver",
    business_name: "Pine Ridge Family Dental",
    website: "https://pineridgedental.example",
    domain: "pineridgedental.example",
    city: "Denver",
    state: "CO",
    country: "United States",
    public_phone: "(303) 555-0118",
    public_email: "office@pineridgedental.example",
    source_url: "https://pineridgedental.example",
    category: "Dental clinic",
    notes: "DEMO. New website, 2024 copyright in footer.",
    tags: ["demo"],
    status: "DRAFT_READY",
    audit: {
      appointment_available: false,
      chatbot_present: false,
      faq_present: true,
      lead_capture_present: false,
      after_hours_help: false,
      mobile_experience: "average",
      contact_flow_clear: true,
      activity_signals: "average",
      opportunities: ["Turn FAQ into an always-on assistant", "Add appointment request capture"],
      observations: [
        "FAQ page exists with 6 questions",
        "No online scheduler or chatbot",
        "Phone number is in the header",
      ],
      confidence: 80,
    },
    score: 88,
    priority: "high",
    reasons: [
      "No chatbot detected on the public website",
      "No obvious online appointment assistant",
      "Weak or missing lead capture",
      "No after-hours assistance detected",
      "Moderate public business activity",
    ],
    estimated_value: "high",
    seedDraft: true,
    seedApproval: "pending",
  },
  {
    slug: "lakeview-chicago",
    business_name: "Lakeview Dental Care",
    website: "https://lakeviewdentalcare.example",
    domain: "lakeviewdentalcare.example",
    city: "Chicago",
    state: "IL",
    country: "United States",
    public_phone: "(773) 555-0166",
    public_email: null,
    source_url: "https://lakeviewdentalcare.example",
    category: "Dental clinic",
    notes: "DEMO. Wix brochure site.",
    tags: ["demo"],
    status: "APPROVED",
    audit: {
      appointment_available: false,
      chatbot_present: false,
      faq_present: false,
      lead_capture_present: true,
      after_hours_help: false,
      mobile_experience: "good",
      contact_flow_clear: true,
      activity_signals: "average",
      opportunities: ["Capture appointment day/time instead of generic contact"],
      observations: [
        "Generic contact form asks for name and message only",
        "No chatbot and no scheduler widget",
      ],
      confidence: 78,
    },
    score: 86,
    priority: "high",
    reasons: [
      "No chatbot detected on the public website",
      "No obvious online appointment assistant",
      "Has a form, but no appointment flow",
      "Weak FAQ / help experience",
      "No after-hours assistance detected",
      "Moderate public business activity",
    ],
    estimated_value: "high",
    seedDraft: true,
    seedApproval: "approved",
  },
  {
    slug: "crescent-nola",
    business_name: "Crescent Moon Dental",
    website: "https://crescentmoondental.example",
    domain: "crescentmoondental.example",
    city: "New Orleans",
    state: "LA",
    country: "United States",
    public_phone: "(504) 555-0133",
    public_email: "info@crescentmoondental.example",
    source_url: "https://crescentmoondental.example",
    category: "Dental clinic",
    notes: "DEMO.",
    tags: ["demo"],
    status: "CONTACTED",
    audit: {
      appointment_available: false,
      chatbot_present: false,
      faq_present: false,
      lead_capture_present: false,
      after_hours_help: true,
      mobile_experience: "average",
      contact_flow_clear: false,
      activity_signals: "average",
      opportunities: ["Replace emergency voicemail-only nights with an assistant"],
      observations: [
        "After-hours note says to leave a voicemail",
        "No chatbot, no booking, no FAQ",
      ],
      confidence: 74,
    },
    score: 84,
    priority: "high",
    reasons: [
      "No chatbot detected on the public website",
      "No obvious online appointment assistant",
      "Weak or missing lead capture",
      "Weak FAQ / help experience",
      "Unclear contact or appointment flow",
      "Moderate public business activity",
    ],
    estimated_value: "medium",
    seedDraft: true,
    seedApproval: "approved",
    response: null,
  },
  {
    slug: "greenfield-boston",
    business_name: "Greenfield Pediatric Dentistry",
    website: "https://greenfieldkidsdental.example",
    domain: "greenfieldkidsdental.example",
    city: "Boston",
    state: "MA",
    country: "United States",
    public_phone: "(617) 555-0177",
    public_email: null,
    source_url: "https://greenfieldkidsdental.example",
    category: "Pediatric dentistry",
    notes: "DEMO. Pediatric-only.",
    tags: ["demo", "pediatric"],
    status: "INTERESTED",
    audit: {
      appointment_available: false,
      chatbot_present: false,
      faq_present: true,
      lead_capture_present: false,
      after_hours_help: false,
      mobile_experience: "good",
      contact_flow_clear: true,
      activity_signals: "strong",
      opportunities: ["Parent FAQ plus appointment request after hours"],
      observations: [
        "Parents FAQ exists",
        "Appointments are phone-only",
        "No chatbot present",
      ],
      confidence: 81,
    },
    score: 83,
    priority: "high",
    reasons: [
      "No chatbot detected on the public website",
      "No obvious online appointment assistant",
      "Weak or missing lead capture",
      "No after-hours assistance detected",
      "Strong public business activity signals",
    ],
    estimated_value: "medium",
    seedDraft: true,
    seedApproval: "approved",
    response: "Asked for a demo next week.",
  },
  {
    slug: "harbor-seattle",
    business_name: "Harbor Periodontics",
    website: "https://harborperio.example",
    domain: "harborperio.example",
    city: "Seattle",
    state: "WA",
    country: "United States",
    public_phone: "(206) 555-0109",
    public_email: "front@harborperio.example",
    source_url: "https://harborperio.example",
    category: "Periodontics",
    notes: "DEMO. Specialist.",
    tags: ["demo", "specialist"],
    status: "DEMO",
    audit: {
      appointment_available: false,
      chatbot_present: false,
      faq_present: true,
      lead_capture_present: true,
      after_hours_help: false,
      mobile_experience: "average",
      contact_flow_clear: true,
      activity_signals: "average",
      opportunities: ["Referral + new-patient intake after hours"],
      observations: [
        "Referral PDF and a contact form, no live scheduler",
        "No chatbot",
      ],
      confidence: 77,
    },
    score: 81,
    priority: "high",
    reasons: [
      "No chatbot detected on the public website",
      "No obvious online appointment assistant",
      "Has a form, but no appointment flow",
      "No after-hours assistance detected",
      "Moderate public business activity",
    ],
    estimated_value: "medium",
    seedDraft: true,
    seedApproval: "approved",
  },
  {
    slug: "valley-sacramento",
    business_name: "Valley View Dental",
    website: "https://valleyviewdental.example",
    domain: "valleyviewdental.example",
    city: "Sacramento",
    state: "CA",
    country: "United States",
    public_phone: "(916) 555-0121",
    public_email: null,
    source_url: "https://valleyviewdental.example",
    category: "Dental clinic",
    notes: "DEMO.",
    tags: ["demo"],
    status: "WON",
    audit: {
      appointment_available: false,
      chatbot_present: false,
      faq_present: false,
      lead_capture_present: true,
      after_hours_help: false,
      mobile_experience: "average",
      contact_flow_clear: true,
      activity_signals: "average",
      opportunities: ["AI appointment assistant for after-hours callers"],
      observations: [
        "Contact form present, no booking widget, no chatbot",
      ],
      confidence: 75,
    },
    score: 79,
    priority: "high",
    reasons: [
      "No chatbot detected on the public website",
      "No obvious online appointment assistant",
      "Has a form, but no appointment flow",
      "Weak FAQ / help experience",
      "No after-hours assistance detected",
      "Moderate public business activity",
    ],
    estimated_value: "medium",
    seedDraft: true,
    seedApproval: "approved",
    response: "Paid $100 setup. Live on their site.",
  },
  {
    slug: "oak-portland",
    business_name: "Oak Street Orthodontics",
    website: "https://oakstreetortho.example",
    domain: "oakstreetortho.example",
    city: "Portland",
    state: "OR",
    country: "United States",
    public_phone: "(503) 555-0188",
    public_email: "smile@oakstreetortho.example",
    source_url: "https://oakstreetortho.example",
    category: "Orthodontics",
    notes: "DEMO.",
    tags: ["demo", "ortho"],
    status: "DRAFT_READY",
    audit: {
      appointment_available: false,
      chatbot_present: false,
      faq_present: true,
      lead_capture_present: true,
      after_hours_help: false,
      mobile_experience: "good",
      contact_flow_clear: false,
      activity_signals: "average",
      opportunities: ["Consult request after hours"],
      observations: [
        "Invisalign consult CTA is a phone number",
        "No chatbot",
      ],
      confidence: 73,
    },
    score: 76,
    priority: "high",
    reasons: [
      "No chatbot detected on the public website",
      "No obvious online appointment assistant",
      "Has a form, but no appointment flow",
      "No after-hours assistance detected",
      "Unclear contact or appointment flow",
      "Moderate public business activity",
    ],
    estimated_value: "medium",
    seedDraft: true,
    seedApproval: "pending",
  },
  {
    slug: "riverbend-nashville",
    business_name: "Riverbend Dental",
    website: "https://riverbenddental.example",
    domain: "riverbenddental.example",
    city: "Nashville",
    state: "TN",
    country: "United States",
    public_phone: "(615) 555-0155",
    public_email: null,
    source_url: "https://riverbenddental.example",
    category: "Dental clinic",
    notes: "DEMO. Score sits on the default threshold.",
    tags: ["demo"],
    status: "QUALIFIED",
    audit: {
      appointment_available: false,
      chatbot_present: false,
      faq_present: true,
      lead_capture_present: true,
      after_hours_help: false,
      mobile_experience: "average",
      contact_flow_clear: true,
      activity_signals: "average",
      opportunities: ["After-hours appointment requests"],
      observations: ["Online form exists but is 'contact us', not booking", "No chatbot"],
      confidence: 70,
    },
    score: 75,
    priority: "high",
    reasons: [
      "No chatbot detected on the public website",
      "No obvious online appointment assistant",
      "Has a form, but no appointment flow",
      "No after-hours assistance detected",
      "Moderate public business activity",
    ],
    estimated_value: "medium",
  },
  {
    slug: "summit-phoenix",
    business_name: "Summit Dental Studio",
    website: "https://summitdentalstudio.example",
    domain: "summitdentalstudio.example",
    city: "Phoenix",
    state: "AZ",
    country: "United States",
    public_phone: "(602) 555-0144",
    public_email: null,
    source_url: "https://summitdentalstudio.example",
    category: "Dental clinic",
    notes: "DEMO. Below default outreach threshold.",
    tags: ["demo", "below-threshold"],
    status: "AUDITED",
    audit: {
      appointment_available: true,
      chatbot_present: false,
      faq_present: false,
      lead_capture_present: true,
      after_hours_help: false,
      mobile_experience: "good",
      contact_flow_clear: true,
      activity_signals: "average",
      opportunities: ["After-hours chatbot on top of existing booking"],
      observations: [
        "Zocdoc-style booking button is present",
        "No chatbot or FAQ",
      ],
      confidence: 72,
    },
    score: 72,
    priority: "medium",
    reasons: [
      "No chatbot detected on the public website",
      "Weak FAQ / help experience",
      "No after-hours assistance detected",
      "Moderate public business activity",
    ],
    estimated_value: "medium",
  },
  {
    slug: "willow-columbus",
    business_name: "Willow Creek Dentistry",
    website: "https://willowcreekdentistry.example",
    domain: "willowcreekdentistry.example",
    city: "Columbus",
    state: "OH",
    country: "United States",
    public_phone: "(614) 555-0120",
    public_email: "hello@willowcreekdentistry.example",
    source_url: "https://willowcreekdentistry.example",
    category: "Dental clinic",
    notes: "DEMO. Below threshold.",
    tags: ["demo", "below-threshold"],
    status: "AUDITED",
    audit: {
      appointment_available: true,
      chatbot_present: false,
      faq_present: true,
      lead_capture_present: true,
      after_hours_help: false,
      mobile_experience: "good",
      contact_flow_clear: true,
      activity_signals: "average",
      opportunities: ["Limited: they already book online"],
      observations: ["Online scheduling is present", "No chatbot"],
      confidence: 68,
    },
    score: 70,
    priority: "medium",
    reasons: [
      "No chatbot detected on the public website",
      "No after-hours assistance detected",
      "Moderate public business activity",
    ],
    estimated_value: "medium",
  },
  {
    slug: "maple-minneapolis",
    business_name: "Maple Grove Dentistry",
    website: "https://maplegrovedentistry.example",
    domain: "maplegrovedentistry.example",
    city: "Minneapolis",
    state: "MN",
    country: "United States",
    public_phone: "(612) 555-0199",
    public_email: null,
    source_url: "https://maplegrovedentistry.example",
    category: "Dental clinic",
    notes: "DEMO.",
    tags: ["demo"],
    status: "RESEARCHING",
    audit: {
      appointment_available: false,
      chatbot_present: true,
      faq_present: false,
      lead_capture_present: true,
      after_hours_help: false,
      mobile_experience: "average",
      contact_flow_clear: true,
      activity_signals: "average",
      opportunities: ["Their widget is generic chat, not appointment-specific"],
      observations: ["Third-party chat bubble present", "No dedicated booking flow"],
      confidence: 64,
    },
    score: 68,
    priority: "medium",
    reasons: [
      "No obvious online appointment assistant",
      "Has a form, but no appointment flow",
      "Weak FAQ / help experience",
      "No after-hours assistance detected",
      "Moderate public business activity",
    ],
    estimated_value: "medium",
  },
  {
    slug: "ironwood-tucson",
    business_name: "Ironwood Family Dentistry",
    website: "https://ironwoodfamilydental.example",
    domain: "ironwoodfamilydental.example",
    city: "Tucson",
    state: "AZ",
    country: "United States",
    public_phone: "(520) 555-0134",
    public_email: null,
    source_url: "https://ironwoodfamilydental.example",
    category: "Dental clinic",
    notes: "DEMO.",
    tags: ["demo"],
    status: "NEW",
    audit: {
      appointment_available: true,
      chatbot_present: false,
      faq_present: false,
      lead_capture_present: false,
      after_hours_help: false,
      mobile_experience: "poor",
      contact_flow_clear: false,
      activity_signals: "weak",
      opportunities: ["Unclear if booking actually works on mobile"],
      observations: ["Book button present but points to a broken calendar page in demo notes"],
      confidence: 50,
    },
    score: 64,
    priority: "medium",
    reasons: [
      "No chatbot detected on the public website",
      "Weak or missing lead capture",
      "Weak FAQ / help experience",
      "No after-hours assistance detected",
      "Unclear contact or appointment flow",
      "Mobile experience looks poor",
    ],
    estimated_value: "medium",
  },
  {
    slug: "coastal-miami",
    business_name: "Coastal Smiles",
    website: "https://coastalsmilesmiami.example",
    domain: "coastalsmilesmiami.example",
    city: "Miami",
    state: "FL",
    country: "United States",
    public_phone: "(305) 555-0160",
    public_email: "team@coastalsmilesmiami.example",
    source_url: "https://coastalsmilesmiami.example",
    category: "Dental clinic",
    notes: "DEMO. Cosmetic-focused.",
    tags: ["demo", "cosmetic"],
    status: "NEW",
    audit: {
      appointment_available: true,
      chatbot_present: false,
      faq_present: true,
      lead_capture_present: true,
      after_hours_help: true,
      mobile_experience: "good",
      contact_flow_clear: true,
      activity_signals: "strong",
      opportunities: ["Weak fit — already well instrumented"],
      observations: ["Online booking, FAQ, and after-hours voicemail tree are present", "No chatbot"],
      confidence: 71,
    },
    score: 58,
    priority: "medium",
    reasons: [
      "No chatbot detected on the public website",
      "Strong public business activity signals",
    ],
    estimated_value: "low",
  },
  {
    slug: "elite-dallas",
    business_name: "Elite Implant Center",
    website: "https://eliteimplantdallas.example",
    domain: "eliteimplantdallas.example",
    city: "Dallas",
    state: "TX",
    country: "United States",
    public_phone: "(214) 555-0181",
    public_email: null,
    source_url: "https://eliteimplantdallas.example",
    category: "Oral surgery",
    notes: "DEMO. High-end implant center with a vendor chatbot.",
    tags: ["demo", "implants"],
    status: "LOST",
    audit: {
      appointment_available: true,
      chatbot_present: true,
      faq_present: true,
      lead_capture_present: true,
      after_hours_help: true,
      mobile_experience: "good",
      contact_flow_clear: true,
      activity_signals: "strong",
      opportunities: [],
      observations: [
        "Vendor chatbot and online consult calendar are both present",
      ],
      confidence: 88,
    },
    score: 51,
    priority: "medium",
    reasons: ["Strong public business activity signals"],
    estimated_value: "low",
    response: "Already using a national dental chatbot vendor.",
  },
  {
    slug: "northstar-detroit",
    business_name: "Northstar Oral Surgery",
    website: "https://northstaroralsurgery.example",
    domain: "northstaroralsurgery.example",
    city: "Detroit",
    state: "MI",
    country: "United States",
    public_phone: "(313) 555-0127",
    public_email: null,
    source_url: "https://northstaroralsurgery.example",
    category: "Oral surgery",
    notes: "DEMO. Low-quality fit.",
    tags: ["demo", "low-fit"],
    status: "DO_NOT_CONTACT",
    audit: {
      appointment_available: true,
      chatbot_present: true,
      faq_present: true,
      lead_capture_present: true,
      after_hours_help: true,
      mobile_experience: "good",
      contact_flow_clear: true,
      activity_signals: "average",
      opportunities: [],
      observations: ["Full patient portal and chatbot already live"],
      confidence: 90,
    },
    score: 47,
    priority: "low",
    reasons: ["Moderate public business activity"],
    estimated_value: "low",
  },
  {
    slug: "metro-nyc",
    business_name: "Metro Dental Group",
    website: "https://metrodentalgroup.example",
    domain: "metrodentalgroup.example",
    city: "New York",
    state: "NY",
    country: "United States",
    public_phone: "(212) 555-0101",
    public_email: "appointments@metrodentalgroup.example",
    source_url: "https://metrodentalgroup.example",
    category: "Dental clinic",
    notes: "DEMO. Large group with a mature stack. Weak prospect.",
    tags: ["demo", "low-fit"],
    status: "AUDITED",
    audit: {
      appointment_available: true,
      chatbot_present: true,
      faq_present: true,
      lead_capture_present: true,
      after_hours_help: true,
      mobile_experience: "good",
      contact_flow_clear: true,
      activity_signals: "strong",
      opportunities: [],
      observations: [
        "Online booking, chatbot, FAQ, and after-hours nurse line are all public",
      ],
      confidence: 92,
    },
    score: 42,
    priority: "low",
    reasons: ["Strong public business activity signals"],
    estimated_value: "low",
  },
  {
    slug: "sunrise-raleigh",
    business_name: "Sunrise Family Dental",
    website: "https://sunrisefamilydental.example",
    domain: "sunrisefamilydental.example",
    city: "Raleigh",
    state: "NC",
    country: "United States",
    public_phone: "(919) 555-0112",
    public_email: null,
    source_url: "https://sunrisefamilydental.example",
    category: "Dental clinic",
    notes: "DEMO. Fresh scout result.",
    tags: ["demo"],
    status: "NEW",
    audit: {
      appointment_available: false,
      chatbot_present: false,
      faq_present: false,
      lead_capture_present: false,
      after_hours_help: false,
      mobile_experience: "unknown",
      contact_flow_clear: null,
      activity_signals: "unknown",
      opportunities: [],
      observations: [],
      confidence: 0,
    },
    score: 0,
    priority: "low",
    reasons: [],
    estimated_value: "low",
  },
  {
    slug: "cedar-boise",
    business_name: "Cedar Park Dental",
    website: "https://cedarparkdental.example",
    domain: "cedarparkdental.example",
    city: "Boise",
    state: "ID",
    country: "United States",
    public_phone: "(208) 555-0148",
    public_email: "desk@cedarparkdental.example",
    source_url: "https://cedarparkdental.example",
    category: "Dental clinic",
    notes: "DEMO. Waiting in scout pool.",
    tags: ["demo"],
    status: "NEW",
    audit: {
      appointment_available: false,
      chatbot_present: false,
      faq_present: false,
      lead_capture_present: false,
      after_hours_help: false,
      mobile_experience: "unknown",
      contact_flow_clear: null,
      activity_signals: "unknown",
      opportunities: [],
      observations: [],
      confidence: 0,
    },
    score: 0,
    priority: "low",
    reasons: [],
    estimated_value: "low",
  },
];

/** Extra pool used by Scout so re-runs can still find quality prospects. */
export const SCOUT_POOL: SampleClinic[] = [
  {
    slug: "lakeside-madison",
    business_name: "Lakeside Family Dentistry",
    website: "https://lakesidefamilydentistry.example",
    domain: "lakesidefamilydentistry.example",
    city: "Madison",
    state: "WI",
    country: "United States",
    public_phone: "(608) 555-0194",
    public_email: null,
    source_url: "https://lakesidefamilydentistry.example",
    category: "Dental clinic",
    notes: "DEMO. Scout discovery.",
    tags: ["demo", "scout"],
    status: "NEW",
    audit: {
      appointment_available: false,
      chatbot_present: false,
      faq_present: false,
      lead_capture_present: false,
      after_hours_help: false,
      mobile_experience: "average",
      contact_flow_clear: false,
      activity_signals: "average",
      opportunities: ["Phone-only booking"],
      observations: ["Public site is a one-page brochure with a phone number"],
      confidence: 60,
    },
    score: 0,
    priority: "low",
    reasons: [],
    estimated_value: "medium",
  },
  {
    slug: "ridgeline-slc",
    business_name: "Ridgeline Dental",
    website: "https://ridgelinedental.example",
    domain: "ridgelinedental.example",
    city: "Salt Lake City",
    state: "UT",
    country: "United States",
    public_phone: "(801) 555-0172",
    public_email: "hello@ridgelinedental.example",
    source_url: "https://ridgelinedental.example",
    category: "Dental clinic",
    notes: "DEMO. Scout discovery.",
    tags: ["demo", "scout"],
    status: "NEW",
    audit: {
      appointment_available: false,
      chatbot_present: false,
      faq_present: true,
      lead_capture_present: false,
      after_hours_help: false,
      mobile_experience: "good",
      contact_flow_clear: true,
      activity_signals: "average",
      opportunities: ["FAQ without intake"],
      observations: ["FAQ page, no scheduler, no chatbot"],
      confidence: 62,
    },
    score: 0,
    priority: "low",
    reasons: [],
    estimated_value: "medium",
  },
  {
    slug: "bayou-houston",
    business_name: "Bayou City Smiles",
    website: "https://bayoucitysmiles.example",
    domain: "bayoucitysmiles.example",
    city: "Houston",
    state: "TX",
    country: "United States",
    public_phone: "(713) 555-0169",
    public_email: null,
    source_url: "https://bayoucitysmiles.example",
    category: "Dental clinic",
    notes: "DEMO. Scout discovery.",
    tags: ["demo", "scout"],
    status: "NEW",
    audit: {
      appointment_available: false,
      chatbot_present: false,
      faq_present: false,
      lead_capture_present: true,
      after_hours_help: false,
      mobile_experience: "poor",
      contact_flow_clear: false,
      activity_signals: "strong",
      opportunities: ["Mobile-unfriendly contact form"],
      observations: ["Contact form exists; no chatbot or booking"],
      confidence: 58,
    },
    score: 0,
    priority: "low",
    reasons: [],
    estimated_value: "high",
  },
  {
    slug: "prairie-omaha",
    business_name: "Prairie Lane Dental",
    website: "https://prairielanedental.example",
    domain: "prairielanedental.example",
    city: "Omaha",
    state: "NE",
    country: "United States",
    public_phone: "(402) 555-0136",
    public_email: null,
    source_url: "https://prairielanedental.example",
    category: "Dental clinic",
    notes: "DEMO. Scout discovery.",
    tags: ["demo", "scout"],
    status: "NEW",
    audit: {
      appointment_available: false,
      chatbot_present: false,
      faq_present: false,
      lead_capture_present: false,
      after_hours_help: false,
      mobile_experience: "average",
      contact_flow_clear: false,
      activity_signals: "average",
      opportunities: ["No digital intake at all"],
      observations: ["Phone and address only on the public homepage"],
      confidence: 55,
    },
    score: 0,
    priority: "low",
    reasons: [],
    estimated_value: "medium",
  },
  {
    slug: "harborview-tampa",
    business_name: "Harborview Family Dental",
    website: "https://harborviewfamilydental.example",
    domain: "harborviewfamilydental.example",
    city: "Tampa",
    state: "FL",
    country: "United States",
    public_phone: "(813) 555-0151",
    public_email: "office@harborviewfamilydental.example",
    source_url: "https://harborviewfamilydental.example",
    category: "Dental clinic",
    notes: "DEMO. Scout discovery.",
    tags: ["demo", "scout"],
    status: "NEW",
    audit: {
      appointment_available: false,
      chatbot_present: false,
      faq_present: false,
      lead_capture_present: false,
      after_hours_help: false,
      mobile_experience: "average",
      contact_flow_clear: true,
      activity_signals: "average",
      opportunities: ["Phone-only hours questions"],
      observations: ["Hours listed; click-to-call only"],
      confidence: 57,
    },
    score: 0,
    priority: "low",
    reasons: [],
    estimated_value: "medium",
  },
];
